plugins {
    id 'fabric-loom' version '1.9-SNAPSHOT' apply false
    id 'net.neoforged.moddev' version '0.1.110' apply false
}

allprojects {
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(Javadoc).tap {
        configureEach {
            options.encoding = 'UTF-8'
            options.charSet = 'UTF-8'
            options.addStringOption('Xdoclint:none', '-quiet')
        }
    }
}
