# Project
version=1.1.0
group=com.florlet.quickalias
java_version=25

# Common
minecraft_version=26.1
mod_name=QuickAlias
mod_author=Florlet
mod_id=quickalias
license=MIT
credits=
description=Lightweight client-side command alias utility. Features a visual editor, hierarchical command menus, dynamic variable resolution, and a quick-access shortcut panel.
minecraft_version_range=[26.1, 26.2)

# Fabric
fabric_version=0.144.0+26.1
fabric_loader_version=0.18.4
modmenu_version=18.0.0-alpha.8

# Forge
forge_version=62.0.0
forge_loader_version_range=[62,)

# NeoForge
neoforge_version=26.1.0.1-beta
neoforge_loader_version_range=[4,)
neo_form_version=26.1-1

# Gradle
org.gradle.jvmargs=-Xmx5G -Dfile.encoding=UTF-8
org.gradle.daemon=false
