# Project
version=1.0.1
group=com.florlet.quickalias
java_version=21

# Common
minecraft_version=1.21
mod_name=QuickAlias
mod_author=Florlet
mod_id=quickalias
license=MIT
credits=
description=Lightweight client-side command alias utility. Features a visual editor, hierarchical command menus, dynamic variable resolution, and a quick-access shortcut panel.
minecraft_version_range=[1.21, 1.21.1)
parchment_minecraft=1.21
parchment_version=2024.06.23

# Fabric
fabric_loader_version=0.15.11
modmenu_version=11.0.0

# Forge
forge_version=51.0.26
forge_loader_version_range=[0,)

# NeoForge
neoforge_version=21.0.158
neoforge_loader_version_range=[4,)
neo_form_version=1.21-20240613.152323

# Gradle
org.gradle.jvmargs=-Xmx5G -Dfile.encoding=UTF-8
org.gradle.daemon=false
