plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[7.0.3,8)'
    id 'net.minecraftforge.accesstransformers' version '5.0.3'
    id 'net.minecraftforge.jarjar' version '0.2.3'
}

repositories {
    maven minecraft.mavenizer
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven

    maven { url "https://repo.spongepowered.org/maven" }

    mavenCentral()
    mavenLocal()
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    accessTransformer = true

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer = at
    }

    runs {
        configureEach {
            workingDir.convention layout.projectDirectory.dir('runs')

            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
        }

        register('client') {
            systemProperty 'forge.enabledGameTestNamespaces', mod_id
        }

        register('server') {
            systemProperty 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }

        register('data') {
            workingDir = layout.projectDirectory.dir('run-data')

            args '--mod', mod_id, '--all', '--output', layout.projectDirectory.dir('src/generated/resources'), '--existing', layout.projectDirectory.dir('src/main/resources')
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation minecraft.dependency('net.minecraftforge:forge:26.1-62.0.0')
    annotationProcessor("org.spongepowered:mixin:0.8.7-SNAPSHOT:processor")

    implementation('net.sf.jopt-simple:jopt-simple:5.0.4') { version { strictly '5.0.4' } }
}

tasks.withType(Test).configureEach {
    enabled = false
}

jar {
    manifest {
        attributes["MixinConfigs"] = "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    }
    archiveBaseName.set("${mod_name}-Forge-mc${minecraft_version}")
}
